#!/usr/bin/env node
/*
  /ame documentation generator.

  Emits the GENERATED half of the /ame brand docs from two sources of truth, so a
  page cannot drift from what it documents:

  1. Foundations pages, from the resolved DTOS token build (build.mjs buildTokens):
     content/ame/foundations/{color,typography,spacing,radii,motion}.mdx. Every
     swatch, specimen, and value is the token's own, projected into MDX exactly as
     build.mjs projects tokens into CSS.

  2. Component + Section catalog pages, from the public props of the brand
     components named in the /ame registry (content/ame/component-registry.json),
     read with react-docgen-typescript (it resolves the inline object-literal prop
     types these components declare, verified on AmeTopBar). One page per
     Components-tier and Sections-tier row: a generated intro, the props table, the
     source, and a live preview for a row the registry marks "documented".

  Modes:
    node tokens/docgen.mjs           write every generated file
    node tokens/docgen.mjs --check   regenerate in memory, diff each against the
                                     committed file, exit 1 on any difference.
                                     This is the parity gate (the B4 pattern: a
                                     generated artifact must equal a fresh run),
                                     wired into `pnpm build`. DECISIONS R-58.

  The parity check lives with the generator, not in check.mjs: its subject is
  extracted TypeScript props, not tokens or CSS, and check.mjs stays free of the
  TS-compiler / react-docgen dependency and fast. This mirrors R-30, which placed
  the JSON-LD check in the render test for the same reason.
*/
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import ts from 'typescript'
import rdt from 'react-docgen-typescript'
import { buildTokens } from './build.mjs'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = join(HERE, '..')
const rel = (p) => relative(REPO, p).split('\\').join('/')

const MARKER = '{/* @generated by tokens/docgen.mjs — do not edit by hand; run: node tokens/docgen.mjs */}'

// ── Small string helpers ────────────────────────────────────────────────────
const humanize = (name) =>
  name.split('-').map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')

// A markdown table cell for CODE-wrapped content (Prop / Type / Default): collapse
// whitespace, escape the pipe and backslash. The backticks protect `<`, `{` from
// MDX, so those are left as-is (a type like `Record<string, X>` must read literally).
const cell = (s) =>
  String(s ?? '').replace(/\\/g, '\\\\').replace(/\r?\n/g, ' ').replace(/\s+/g, ' ').replace(/\|/g, '\\|').trim()

// A markdown table cell for PLAIN text (a prop Description): same collapse, plus
// the MDX-significant characters escaped to HTML entities. A description extracted
// from JSDoc can contain `<html lang>` or `{x}`, which MDX would otherwise parse as
// JSX or an expression and fail the build.
const cellText = (s) =>
  cell(s).replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\{/g, '&#123;').replace(/\}/g, '&#125;')

// A value shown as a JSX string attribute, in double quotes. Token CSS literals
// never contain a double quote (font families use single quotes), so this is
// exact for our inputs.
const attr = (s) => `"${String(s)}"`

// A YAML double-quoted scalar for frontmatter.
const yaml = (s) => `"${String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`

// ── Foundations ─────────────────────────────────────────────────────────────
const { tokens } = buildTokens()
const byLayerType = (layer, type) => tokens.filter((t) => t.layer === layer && t.type === type)
const firstSeg = (t) => t.path.split('.')[0]

function grid(items, tag, extra = () => '') {
  const lines = items.map(
    (t) => `<${tag} path=${attr(t.path)} cssvar=${attr(t.cssName)} value=${attr(t.css)}${extra(t)} />`,
  )
  return `<AmeFoundationGrid>\n${lines.join('\n')}\n</AmeFoundationGrid>`
}

function foundationsPage({ slug, title, description, sections }) {
  const body = sections
    .filter((s) => s.items.length)
    .map((s) => `## ${s.heading}\n\n${grid(s.items, s.tag, s.extra)}`)
    .join('\n\n')
  return (
    `---\n` +
    `title: ${yaml(title)}\n` +
    `description: ${yaml(description)}\n` +
    `---\n\n` +
    `${MARKER}\n\n` +
    `${description} Every value on this page is the token's own, generated from ` +
    `\`tokens/{base,semantic,component}/*.json\` through \`tokens/build.mjs\`, so it ` +
    `cannot drift from the source; the token is the one home and this page is a ` +
    `generated view of it.\n\n` +
    `${body}\n`
  )
}

function foundationsFiles() {
  const files = new Map()

  files.set('content/ame/foundations/color.mdx', foundationsPage({
    slug: 'color',
    title: 'Color',
    description: 'The ame color scales: base ramps and the semantic roles that reference them.',
    sections: [
      { heading: 'Base ramps', tag: 'AmeSwatch', items: byLayerType('base', 'color') },
      { heading: 'Semantic roles', tag: 'AmeSwatch', items: byLayerType('semantic', 'color') },
    ],
  }))

  files.set('content/ame/foundations/typography.mdx', foundationsPage({
    slug: 'typography',
    title: 'Typography',
    description: 'The ame type scale: families, sizes, and weights.',
    sections: [
      { heading: 'Families', tag: 'AmeFontFamily', items: byLayerType('base', 'fontFamily') },
      {
        heading: 'Sizes',
        tag: 'AmeTypeSpecimen',
        items: [...byLayerType('base', 'dimension'), ...byLayerType('semantic', 'dimension')].filter(
          (t) => /(^|\.)(font|type)\b/.test(t.path) && /size/.test(t.path),
        ),
      },
      { heading: 'Weights', tag: 'AmeWeightSpecimen', items: byLayerType('base', 'fontWeight') },
    ],
  }))

  files.set('content/ame/foundations/spacing.mdx', foundationsPage({
    slug: 'spacing',
    title: 'Spacing',
    description: 'The ame spacing scale: the base unit ramp and the semantic space roles.',
    sections: [
      { heading: 'Base units', tag: 'AmeSpaceBar', items: tokens.filter((t) => t.layer === 'base' && firstSeg(t) === 'unit') },
      { heading: 'Semantic space', tag: 'AmeSpaceBar', items: tokens.filter((t) => t.layer === 'semantic' && firstSeg(t) === 'space') },
    ],
  }))

  files.set('content/ame/foundations/radii.mdx', foundationsPage({
    slug: 'radii',
    title: 'Radii',
    description: 'The ame corner-radius scale and border widths.',
    sections: [
      { heading: 'Radius', tag: 'AmeRadiusBox', items: tokens.filter((t) => t.layer === 'base' && firstSeg(t) === 'radius') },
      { heading: 'Border width', tag: 'AmeRadiusBox', items: tokens.filter((t) => firstSeg(t) === 'border' && t.type === 'dimension') },
    ],
  }))

  const motionExtra = (t) => ` kind=${attr(t.type === 'cubicBezier' ? 'easing' : 'duration')}`
  files.set('content/ame/foundations/motion.mdx', foundationsPage({
    slug: 'motion',
    title: 'Motion',
    description: 'The ame motion scale: durations and easing curves.',
    sections: [
      { heading: 'Durations', tag: 'AmeMotionDemo', extra: motionExtra, items: byLayerType('base', 'duration') },
      { heading: 'Easings', tag: 'AmeMotionDemo', extra: motionExtra, items: byLayerType('base', 'cubicBezier') },
      {
        heading: 'Semantic motion',
        tag: 'AmeMotionDemo',
        extra: motionExtra,
        items: tokens.filter((t) => t.layer === 'semantic' && firstSeg(t) === 'motion'),
      },
    ],
  }))

  return files
}

// ── Catalog (component + section props) ─────────────────────────────────────
const registry = JSON.parse(readFileSync(join(REPO, 'content/ame/component-registry.json'), 'utf8'))
const CATALOG_TIERS = { Components: 'components', Sections: 'sections' }

function docgenParser() {
  return rdt.withCompilerOptions(
    {
      esModuleInterop: true,
      jsx: ts.JsxEmit.ReactJSX,
      module: ts.ModuleKind.ESNext,
      target: ts.ScriptTarget.ESNext,
      moduleResolution: ts.ModuleResolutionKind.Bundler,
      baseUrl: REPO,
      paths: { '@/*': ['*'] },
    },
    {
      savePropValueAsString: true,
      shouldExtractLiteralValuesFromEnum: true,
      shouldRemoveUndefinedFromOptional: true,
      // Drop props whose declaration is in node_modules (React DOM/SVG props etc.):
      // the catalog documents each component's own API, not inherited DOM surface.
      propFilter: (prop) => !(prop.parent && /node_modules/.test(prop.parent.fileName)),
    },
  )
}

function renderType(t) {
  if (!t) return 'unknown'
  if ((t.name === 'enum' || t.name === 'union') && Array.isArray(t.value) && t.value.length) {
    return t.value.map((v) => String(v.value)).join(' | ')
  }
  return t.name
}

function propsTable(props) {
  const names = Object.keys(props).sort()
  if (!names.length) return '_This component takes no public props._'
  const head = '| Prop | Type | Required | Default | Description |\n| --- | --- | --- | --- | --- |'
  const rows = names.map((name) => {
    const p = props[name]
    const type = cell(renderType(p.type))
    const required = p.required ? 'yes' : '—'
    const def = p.defaultValue && p.defaultValue.value != null ? '`' + cell(p.defaultValue.value) + '`' : '—'
    const desc = cellText(p.description)
    return `| \`${cell(name)}\` | \`${type}\` | ${required} | ${def} | ${desc} |`
  })
  return [head, ...rows].join('\n')
}

// ── Consumption contract (the API for a token-driven / prop-less component) ──
// A brand component with no props is not API-less: its real contract is the CSS
// custom properties it binds by name, the React context it needs, and the DOM
// props it forwards. That contract is derived from the component source so it
// cannot be faked or drift, and it stands in for a props table where there is
// none (DECISIONS R-64). The provider map is the two excluded provider files
// (invariants.json > ame_registry.excluded; DECISIONS R-57).
const PROVIDERS = {
  usePortfolioTheme: '`PortfolioThemeProvider` (`components/portfolio/portfolio-theme.tsx`)',
  usePortfolioA11y: '`PortfolioA11yProvider` (`components/portfolio/a11y-prefs.tsx`)',
}

function sourceContract(source) {
  const src = readFileSync(join(REPO, source), 'utf8')
  // The `var(--…)` custom properties the source binds by name.
  const reads = [...new Set([...src.matchAll(/var\(\s*(--[a-z0-9-]+)/gi)].map((m) => m[1]))].sort()
  // React context this component reads (from the provider hooks it calls).
  const requires = Object.keys(PROVIDERS)
    .filter((h) => new RegExp(`\\b${h}\\b`).test(src))
    .sort()
    .map((h) => PROVIDERS[h])
  // Whether it spreads a DOM props type onto its root element.
  const forwards = /:\s*SVGProps</.test(src)
    ? 'svg'
    : /:\s*(?:React\.)?(?:HTMLAttributes|ComponentPropsWithoutRef|ComponentProps)</.test(src)
      ? 'html'
      : null
  return { reads, requires, forwards }
}

function contractSection(c) {
  const lines = [
    'Render this component inside the `.portfolio-root` ame token scope — the `/ame` ' +
      'docs layout and every portfolio surface provide it, and it is where the tokens below ' +
      'resolve.',
    '',
  ]
  if (c.reads.length) {
    lines.push('**Binds these tokens** — the CSS custom properties it reads by name through `var()`:', '')
    lines.push(c.reads.map((v) => `\`${v}\``).join(', '))
  } else {
    lines.push(
      '**Binds no tokens by name.** It inherits type and color from the ame scope and reads no ' +
        'custom property directly.',
    )
  }
  lines.push('')
  lines.push(
    c.requires.length
      ? `**Requires React context:** ${c.requires.join(', ')}.`
      : '**Requires no React context.**',
  )
  if (c.forwards) {
    lines.push('')
    lines.push(
      c.forwards === 'svg'
        ? '**Forwards DOM props:** standard `<svg>` attributes are spread onto the root element.'
        : '**Forwards DOM props:** standard HTML attributes are spread onto the root element.',
    )
  }
  return lines.join('\n')
}

function catalogFiles(parser) {
  const rows = registry.components.filter((r) => CATALOG_TIERS[r.tier])
  // One TS program over every catalog source: far cheaper than one per file.
  const paths = rows.map((r) => join(REPO, r.source))
  const parsed = parser.parse(paths)
  const byFile = new Map()
  for (const d of parsed) {
    const key = rel(d.filePath)
    if (!byFile.has(key)) byFile.set(key, [])
    byFile.get(key).push(d)
  }

  const files = new Map()
  for (const r of rows) {
    const dir = CATALOG_TIERS[r.tier]
    const title = humanize(r.name)
    const docs = (byFile.get(r.source) ?? []).slice().sort((a, b) => a.displayName.localeCompare(b.displayName))
    const symbols = docs.map((d) => d.displayName)
    const animated = r.animated === true
    const documented = r.status === 'documented'

    const description =
      `${symbols[0] ?? title}: a ${r.tier}-tier ame brand component` +
      `${animated ? ', animated' : ''}. Props and source generated from ${r.source}.`

    // A documented animated row shows an interactive playground (its `playground`
    // field, checked by AM3); a documented static row shows a live preview.
    const hasPlayground = documented && animated && Boolean(r.playground)

    // Generated intro.
    const symbolList = symbols.length ? symbols.map((s) => `\`${s}\``).join(', ') : `\`${title}\``
    let intro =
      `${symbolList} ${symbols.length > 1 ? 'are' : 'is'} part of the ame brand system, ` +
      `in the ${r.tier} tier. The source is \`${r.source}\`. `
    if (hasPlayground) {
      intro +=
        'It is animated, so this page shows an interactive playground wired to its real ' +
        'animation parameters, the public props, and the full source.'
    } else if (documented) {
      intro += 'This page shows a live preview, the public props, and the full source.'
    } else if (animated && r.playground_deferred_because) {
      intro +=
        'It is animated but is not sandboxed in a doc page: ' +
        r.playground_deferred_because +
        ' This page is its generated catalog entry: the public props and the full source.'
    } else if (animated) {
      intro +=
        'It is marked animated; this page is its generated catalog entry: the public ' +
        'props and the full source.'
    } else {
      intro +=
        'This page is its generated catalog entry: the public props and the full source. ' +
        'A live preview is not mounted this phase.'
    }

    // The API section is the props tables for the symbols that HAVE props; a
    // symbol with none (a prop-less component, or a plain exported const like a
    // duration) gets no empty table. When nothing on the page has props, the API
    // is the consumption contract below, and this says so rather than showing a
    // fake empty table (DECISIONS R-64).
    const withProps = docs.filter((d) => Object.keys(d.props).length)
    const api = withProps.length
      ? withProps.map((d) => `### ${d.displayName}\n\n${propsTable(d.props)}`).join('\n\n')
      : 'This component exposes no configurable props; its API is the consumption contract below.'

    const contract = contractSection(sourceContract(r.source))

    // The interactive block: a playground for an animated+documented row, a live
    // preview for a static documented row, a link-out disclosure for an animated
    // row deferred out of a doc box (the viewer, the full-page overlays), else none.
    let previewBlock = ''
    if (hasPlayground) {
      previewBlock = `## Playground\n\n<AmePlaygroundEmbed name=${attr(r.name)} />\n\n`
    } else if (documented) {
      previewBlock = `## Preview\n\n<AmePreview name=${attr(r.name)} />\n\n`
    } else if (animated && r.playground_deferred_because && r.live_route) {
      previewBlock =
        `## Live behavior\n\n` +
        `No playground is embedded here. ${r.playground_deferred_because} ` +
        `See it live at [\`${r.live_route}\`](${r.live_route}).\n\n`
    }

    const content =
      `---\n` +
      `title: ${yaml(title)}\n` +
      `description: ${yaml(description)}\n` +
      `---\n\n` +
      `${MARKER}\n\n` +
      `${intro}\n\n` +
      `${previewBlock}` +
      `## API\n\n${api}\n\n` +
      `## Consumption contract\n\n${contract}\n\n` +
      `## Source\n\n<ComponentSource path=${attr(r.source)} />\n`

    files.set(`content/ame/${dir}/${r.name}.mdx`, content)
  }
  return files
}

// ── Assemble, then write or check ───────────────────────────────────────────
function generate() {
  const files = new Map([...foundationsFiles()])
  const parser = docgenParser()
  for (const [k, v] of catalogFiles(parser)) files.set(k, v)
  return files
}

function main() {
  const check = process.argv.includes('--check')
  const files = generate()

  if (check) {
    const diffs = []
    for (const [path, content] of files) {
      const abs = join(REPO, path)
      const on = existsSync(abs) ? readFileSync(abs, 'utf8') : null
      if (on !== content) diffs.push(path)
    }
    if (diffs.length) {
      console.error(
        `docgen parity FAIL: ${diffs.length} generated file(s) differ from a fresh run.\n` +
          diffs.map((d) => `  ${d}`).join('\n') +
          `\nRegenerate with: node tokens/docgen.mjs`,
      )
      process.exit(1)
    }
    console.log(`docgen parity PASS: ${files.size} generated /ame file(s) match a fresh run.`)
    return
  }

  for (const [path, content] of files) {
    const abs = join(REPO, path)
    mkdirSync(dirname(abs), { recursive: true })
    writeFileSync(abs, content)
  }
  console.log(`docgen wrote ${files.size} generated /ame file(s).`)
}

main()
