/* ame@0.1.0 · DTOS 2025.10 · generated, do not edit */
/*
  GENERATED by packages/ame-tokens/build.mjs. Do not edit by hand.
  Source of truth: packages/ame-tokens/resolver.json + the token JSON (DTOS 2025.10)

  The typed surface of the token system. tokens.css is its CSS home; this is the
  home a component binds by name. Values live in the stylesheet and are never
  carried here, so this stays three string builders and no runtime resolution.
*/

/** Every recipe: its root class, its slots, and its axes with their contexts. */
export const RECIPES = Object.freeze({
  "expertise-card": {
    class: "ame-expertise-card",
    element: "components/portfolio/expertise-card.tsx",
    slots: ["root", "list", "cell", "block", "label", "value"],
    axes: {
      "viewport": {
        default: "base",
        contexts: ["base", "sm", "lg"],
      },
      "layout": {
        attribute: "data-layout",
        default: "expertise",
        contexts: ["expertise", "term-sheet"],
      },
    },
  },
})

/** A custom property, as a CSS value. The name is checked by the union in tokens.d.ts. */
export const token = (name) => `var(${name})`

/** A slot's class. Root takes the recipe's own class; every other slot is suffixed. */
export const slot = (name, part) =>
  part === 'root' ? RECIPES[name].class : `${RECIPES[name].class}__${part}`

/**
 * A recipe's root props: its class, plus one data attribute per attribute axis.
 * An axis left unset falls back to its declared default, so the attribute is
 * always present and the DOM says which context is in force rather than leaving
 * it to be inferred from the absence of a selector. A media axis takes no
 * attribute — the viewport selects it, not the markup — so it never appears here.
 */
export function recipe(name, variants = {}) {
  const spec = RECIPES[name]
  const props = { className: spec.class }
  for (const [axis, a] of Object.entries(spec.axes))
    if (a.attribute) props[a.attribute] = variants[axis] ?? a.default
  return props
}

/* The counts the docs state, derived here so no surface transcribes them. */
export const ROOT_PROPS = 336
export const DARK_REPOINTS = 6
export const COLOR_TOKENS = 107
export const COLOR_SRGB = 86
export const COLOR_OKLCH = 21
